TARGET=opencv-test
CXXFLAGS=-std=c++11 -lGL -lglfw -lGLEW -lSOIL `pkg-config opencv --cflags --libs`
DEBUGFLAGS=-ggdb
compile: $(TARGET).cpp
	g++ $(TARGET).cpp -o $(TARGET) $(CXXFLAGS) 
debug: $(TARGET).cpp
	g++ $(DEBUGFLAGS) $(TARGET).cpp -o $(TARGET) $(CXXFLAGS) 
valgrind: compile
	valgrind ./$(TARGET)
run: compile
	./$(TARGET)
